#!/usr/bin/env python3
"""
Discover all checkov submodules that are normally loaded via glob in __init__.py,
so Nuitka can include them (Option A: config file, Option B: CLI --include-module flags).

Run from repo root after: pipenv install (with checkov on path).
Outputs:
  - nuitka-generated/checkov.nuitka-package.config.yml (Option A)
  - nuitka-generated/nuitka-include-modules.txt (Option B: one module per line)
"""

from __future__ import print_function

import pkgutil
import sys
from pathlib import Path


def discover_checkov_submodules():
    """Discover all submodules under the checkov package."""
    try:
        import checkov
    except ImportError as e:
        print("Error: checkov must be importable. Run from repo root after pipenv install.", file=sys.stderr)
        raise SystemExit(1) from e

    root = "checkov"
    modules = []
    try:
        if hasattr(checkov, "__path__"):
            for _imp, name, _ispkg in pkgutil.walk_packages(checkov.__path__, prefix=root + "."):
                modules.append(name)
        else:
            modules.append(root)
    except Exception as e:
        print("Error discovering modules:", e, file=sys.stderr)
        raise SystemExit(1) from e

    return sorted(modules)


def write_nuitka_config(modules, out_path):
    """Write Nuitka package config YAML (Option A)."""
    indent = "  "
    lines = [
        "# Generated by scripts/discover_checkov_modules.py",
        "# Use with: --user-package-configuration-file=nuitka-generated/checkov.nuitka-package.config.yml",
        "",
        "- module-name: 'checkov'",
        "  implicit-imports:",
        "    depends:",
    ]
    for m in modules:
        lines.append(indent + "- '{}'".format(m))
    lines.extend([
        "",
        "  data-files:",
        "    dest_path: '.'",
        "    dirs:",
        "      - '.'",
        "    patterns:",
        "      - '*.yaml'",
        "      - '*.yml'",
    ])
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("Wrote {} ({} modules)".format(out_path, len(modules)))


def write_modules_list(modules, out_path):
    """Write one module per line for Option B."""
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(modules) + "\n", encoding="utf-8")
    print("Wrote {} ({} modules)".format(out_path, len(modules)))


def main():
    root = Path(__file__).resolve().parent.parent
    out_dir = root / "nuitka-generated"
    out_dir.mkdir(exist_ok=True)

    modules = discover_checkov_submodules()
    if not modules:
        print("No checkov submodules found.", file=sys.stderr)
        sys.exit(1)

    config_path = out_dir / "checkov.nuitka-package.config.yml"
    list_path = out_dir / "nuitka-include-modules.txt"

    write_nuitka_config(modules, config_path)
    write_modules_list(modules, list_path)

    print("\nOption B: use nuitka-include-modules.txt with --include-module in workflow.", file=sys.stderr)


if __name__ == "__main__":
    main()
